import express from "express";
import { router as index } from "./api/index";
import { router as user } from "./api/user/user";
import { router as board } from "./api/BoardAndTasks/board";
import { router as otp } from "./api/authen/otp";
import { router as signin_up } from "./api/authen/signin_up";
import { router as googlelogin } from "./api/authen/google_login";
import { router as resetpassword } from "./api/resetpassword/resetpassword";
import { router as admin } from "./api/admin/edituser";
import { router as profile } from "./api/user/profile";
import { router as attachments } from "./api/attachments/attachments";
import { router as share } from "./api/BoardAndTasks/share";
import { router as tasks } from "./api/BoardAndTasks/task";
import verify_captcha from "./api/authen/verify_captcha";
import bodyParser from "body-parser";

export const app = express();

app.use(bodyParser.json());
app.use("/", index);
app.use("/user", user);
app.use("/board", board);
app.use("/board/share", share);
app.use("/board", tasks);
app.use("/otp", otp);
app.use("/signin_up", signin_up);
app.use("/google", googlelogin);
app.use("/resetpassword", resetpassword);
app.use("/admin", admin);
app.use("/profile", profile);
app.use("/attachments", attachments);
app.use("/verify", verify_captcha);
// app.use("/share", share);
